import Link from "next/link";
import { ScrollProgress } from "@/components/public/scroll-progress";

const moments = [["01", "DISCOVER", "Find the curiosity that pulls you forward."], ["02", "CONNECT", "Meet the people who could change your first year."], ["03", "CREATE", "Turn bright ideas into something real."], ["04", "DAWN", "Leave with a beginning, not just a memory."]];
const timeline = [["04:00", "ARRIVE", "The night opens"], ["06:00", "IGNITE", "Energy in motion"], ["00:00", "MIDNIGHT", "The unexpected"], ["08:00", "DAWN", "A new beginning"]];

export default function Home() {
  return <main className="night-sky min-h-screen overflow-hidden text-white"><ScrollProgress /><section className="relative mx-auto flex min-h-screen max-w-7xl flex-col px-5 py-6 sm:px-10"><div className="orb orb-one"/><div className="orb orb-two"/><header className="relative z-10 flex items-center justify-between"><p className="font-black tracking-[.24em] text-cyan-200">NOVICIA ’26</p><div className="flex items-center gap-4"><span className="hidden text-xs font-bold tracking-[.16em] text-slate-400 sm:block">26—27 SEP</span><Link href="/register" className="magnetic-button">GET YOUR PASS <span>↗</span></Link></div></header><div className="relative z-10 flex flex-1 flex-col justify-center py-20"><p className="animate-rise text-xs font-bold tracking-[.32em] text-violet-200">IEDC LBSCEK · AN OVERNIGHT EXPERIENCE</p><h1 className="hero-type mt-6 max-w-6xl">NOT YOUR<br/><em>FIRST</em> NIGHT.</h1><div className="mt-10 flex max-w-2xl flex-col gap-6 sm:flex-row sm:items-end"><p className="max-w-md text-lg leading-8 text-slate-300">A night designed to turn strangers into teammates, questions into ideas, and first steps into momentum.</p><a href="#journey" className="group flex items-center gap-3 text-sm font-bold text-cyan-200">SCROLL TO BEGIN <span className="inline-flex size-9 items-center justify-center rounded-full border border-cyan-200/40 transition group-hover:translate-y-1">↓</span></a></div></div><div className="relative z-10 grid grid-cols-2 border-t border-white/10 py-5 text-xs font-bold tracking-[.14em] text-slate-400 sm:grid-cols-4">{["4 PM / START", "12 AM / SHIFT", "8 AM / DAWN", "30 / SEATS"].map((item) => <span key={item}>{item}</span>)}</div></section>

    <section id="journey" className="relative bg-[#0b1030] px-5 py-24 sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 lg:flex-row"><div><p className="section-kicker">THE NOVICIA FREQUENCY</p><h2 className="display-title mt-4 max-w-xl">A night with its own <span>pulse.</span></h2></div><p className="max-w-sm self-end leading-7 text-slate-300">There is no spectator seat here. Every moment invites you to show up, take part, and discover what happens next.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{moments.map(([number, title, copy], i) => <article key={title} className="reveal-card group relative overflow-hidden rounded-3xl p-7 sm:p-10"><span className="font-mono text-sm text-cyan-200">{number}</span><h3 className="mt-20 text-4xl font-black tracking-[-.05em]">{title}</h3><p className="mt-4 max-w-xs text-slate-300">{copy}</p><span className="absolute -bottom-9 -right-2 text-9xl font-black text-white/[.035] transition duration-500 group-hover:-translate-y-3">0{i + 1}</span></article>)}</div></div></section>

    <section className="relative overflow-hidden bg-[#f3f4ff] px-5 py-24 text-[#11142d] sm:px-10"><div className="sunrise absolute -top-36 left-1/2 size-[35rem] -translate-x-1/2 rounded-full"/><div className="relative mx-auto max-w-7xl"><p className="section-kicker text-violet-700">THE NIGHT IN MOTION</p><div className="mt-10 grid gap-6 lg:grid-cols-4">{timeline.map(([time, title, copy], i) => <article key={time} className="rounded-3xl bg-white/70 p-6 shadow-xl shadow-indigo-950/5 backdrop-blur"><p className="font-mono text-sm text-violet-700">{time}</p><div className="mt-14 size-3 rounded-full bg-gradient-to-br from-violet-500 to-cyan-400"/><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-2 text-sm text-slate-600">{copy}</p><p className="mt-7 font-mono text-xs text-slate-400">0{i + 1} — 04</p></article>)}</div></div></section>

    <section className="relative bg-[#080a19] px-5 py-28 text-center sm:px-10"><div className="mx-auto max-w-3xl"><p className="section-kicker">ONLY 30 SEATS</p><h2 className="display-title mt-5">Your first chapter starts <span>after dark.</span></h2><p className="mx-auto mt-7 max-w-xl text-lg leading-8 text-slate-300">First come, first served. Register now, receive your digital pass, and bring your curiosity to ASAP OpenMind.</p><div className="mt-10 flex flex-wrap justify-center gap-4"><Link href="/register" className="magnetic-button text-base">RESERVE YOUR SEAT <span>↗</span></Link><Link href="/faq" className="rounded-xl border border-white/20 px-6 py-3.5 font-bold transition hover:bg-white/10">QUESTIONS?</Link></div></div></section>
  </main>;
}
